### ISSUE TITLE
clij3 imglib2 break bigdataviewer

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/clij3#15]
When installing clij3 along with the new imglib2 jar, it break bigdataview with the following error. Not related to clij3 it self but put it here as a warning until fix is done.

```java
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval; on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at btbvv.core.InteractiveGLDisplayCanvas$MyGLJPanel.paintComponent(InteractiveGLDisplayCanvas.java:141)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1978)
	at java.awt.Window.paint(Window.java:3906)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval;
	at btbvv.core.render.DefaultSimpleStackManager.copyToBufferU16(DefaultSimpleStackManager.java:159)
	at btbvv.core.render.DefaultSimpleStackManager.uploadToTextureU16(DefaultSimpleStackManager.java:150)
	at btbvv.core.render.DefaultSimpleStackManager.lambda$0(DefaultSimpleStackManager.java:83)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
	at btbvv.core.render.DefaultSimpleStackManager.getSimpleVolume(DefaultSimpleStackManager.java:83)
	at btbvv.core.render.VolumeRenderer.draw(VolumeRenderer.java:346)
	at btbvv.core.VolumeViewerPanel$1.display(VolumeViewerPanel.java:1061)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 49 more
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval; on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at btbvv.core.InteractiveGLDisplayCanvas$MyGLJPanel.paintComponent(InteractiveGLDisplayCanvas.java:141)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval;
	at btbvv.core.render.DefaultSimpleStackManager.copyToBufferU16(DefaultSimpleStackManager.java:159)
	at btbvv.core.render.DefaultSimpleStackManager.uploadToTextureU16(DefaultSimpleStackManager.java:150)
	at btbvv.core.render.DefaultSimpleStackManager.lambda$0(DefaultSimpleStackManager.java:83)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
	at btbvv.core.render.DefaultSimpleStackManager.getSimpleVolume(DefaultSimpleStackManager.java:83)
	at btbvv.core.render.VolumeRenderer.draw(VolumeRenderer.java:346)
	at btbvv.core.VolumeViewerPanel$1.display(VolumeViewerPanel.java:1061)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 34 more
Exception in thread "PainterThread" com.jogamp.opengl.GLException: java.lang.reflect.InvocationTargetException
	at com.jogamp.opengl.awt.GLJPanel.display(GLJPanel.java:465)
	at btbvv.core.InteractiveGLDisplayCanvas.display(InteractiveGLDisplayCanvas.java:322)
	at btbvv.core.VolumeViewerPanel.paint(VolumeViewerPanel.java:549)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:87)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at com.jogamp.opengl.awt.GLJPanel.display(GLJPanel.java:463)
	... 3 more
Caused by: com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at btbvv.core.InteractiveGLDisplayCanvas$MyGLJPanel.paintComponent(InteractiveGLDisplayCanvas.java:141)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at com.jogamp.opengl.awt.GLJPanel$12.run(GLJPanel.java:1535)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at btbvv.core.backend.jogl.JoglGpuContext.target(JoglGpuContext.java:402)
	at btbvv.core.backend.jogl.JoglGpuContext.lambda$3(JoglGpuContext.java:354)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at btbvv.core.backend.jogl.JoglGpuContext.getTextureId(JoglGpuContext.java:349)
	at btbvv.core.backend.jogl.JoglGpuContext.bindTexture(JoglGpuContext.java:143)
	at btbvv.core.shadergen.AbstractShader.bindSamplers(AbstractShader.java:206)
	at btbvv.core.render.MultiVolumeShaderMip.bindSamplers(MultiVolumeShaderMip.java:514)
	at btbvv.core.render.VolumeRenderer.draw(VolumeRenderer.java:368)
	at btbvv.core.VolumeViewerPanel$1.display(VolumeViewerPanel.java:1061)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 26 more
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at btbvv.core.InteractiveGLDisplayCanvas$MyGLJPanel.paintComponent(InteractiveGLDisplayCanvas.java:141)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at btbvv.core.backend.jogl.JoglGpuContext.target(JoglGpuContext.java:402)
	at btbvv.core.backend.jogl.JoglGpuContext.lambda$3(JoglGpuContext.java:354)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at btbvv.core.backend.jogl.JoglGpuContext.getTextureId(JoglGpuContext.java:349)
	at btbvv.core.backend.jogl.JoglGpuContext.bindTexture(JoglGpuContext.java:143)
	at btbvv.core.shadergen.AbstractShader.bindSamplers(AbstractShader.java:206)
	at btbvv.core.render.MultiVolumeShaderMip.bindSamplers(MultiVolumeShaderMip.java:514)
	at btbvv.core.render.VolumeRenderer.draw(VolumeRenderer.java:368)
	at btbvv.core.VolumeViewerPanel$1.display(VolumeViewerPanel.java:1061)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 34 more
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.doPaintComponent(GLJPanel.java:2095)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:569)
	at btbvv.core.InteractiveGLDisplayCanvas$MyGLJPanel.paintComponent(InteractiveGLDisplayCanvas.java:141)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at btbvv.core.backend.jogl.JoglGpuContext.target(JoglGpuContext.java:402)
	at btbvv.core.backend.jogl.JoglGpuContext.lambda$3(JoglGpuContext.java:354)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at btbvv.core.backend.jogl.JoglGpuContext.getTextureId(JoglGpuContext.java:349)
	at btbvv.core.backend.jogl.JoglGpuContext.bindTexture(JoglGpuContext.java:143)
	at btbvv.core.shadergen.AbstractShader.bindSamplers(AbstractShader.java:206)
	at btbvv.core.render.MultiVolumeShaderMip.bindSamplers(MultiVolumeShaderMip.java:514)
	at btbvv.core.render.VolumeRenderer.draw(VolumeRenderer.java:368)
	at btbvv.core.VolumeViewerPanel$1.display(VolumeViewerPanel.java:1061)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLJPanel$Updater.display(GLJPanel.java:1446)
	at com.jogamp.opengl.awt.GLJPanel$10.run(GLJPanel.java:1521)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 34 more
```

**Comment by StRigaud** [comment]
@tpietzsch 👋

**Comment by StRigaud** [comment]
I think this is resolved now with new `pom-scijava` version `39.0.0` and higher. we can close.
